# Generated by Django 3.0.5 on 2020-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200430_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='authtoken_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
